### ISSUE TITLE
Wrong reactive version installed with wheelhouse override

### ISSUE THREAD

**Issue by xannz** [juju-solutions/charms.reactive#149] opened 2018-01-10 15:35 UTC
I've built a charm with the latest code from git using a wheelhouse override. Both the stable and latest version are present in the wheelhouse folder in the built charm. After deployment, the old version is installed instead of the latest one. Even with `venv: true` it installs the old version inside the virtual env. If I manually remove the old version from the wheelhouse folder of the built charm, the new version gets installed. 

This happened with a subordinate charm. Normal charms do not appear to have this issue.

**Comment by johnsca** [comment] 2018-01-16 09:01
The root cause of this is juju/charm-tools#381 which is what causes both versions to end up in the wheelhouse directory in the built charm.  A workaround until that is fixed would be to manually remove the incorrect version from the wheelhouse directory of the built charm.

**Comment by galgalesh** [comment] 2018-01-22 15:54
Fix has been committed to master of charm-tools. This will be fixed when the next version of charm-tools is released.

**Closed by galgalesh** 2018-01-22 15:54 UTC
